# Generated by Django 5.0.2 on 2025-12-01 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0002_alter_loan_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='updated_at',
            new_name='fechaActualizacion',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='created_at',
            new_name='fechaCreacion',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='updated_at',
            new_name='fechaActualizacion',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='created_at',
            new_name='fechaCreacion',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='updated_at',
            new_name='fechaActualizacion',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='created_at',
            new_name='fechaCreacion',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='updated_at',
            new_name='fechaActualizacion',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='created_at',
            new_name='fechaCreacion',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='cancel_reason',
            new_name='razonCancelacion',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo', to='sistema_buap_api.lab'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento')], default='ACTIVO', max_length=16),
        ),
    ]
