# Generated by Django 5.0.2 on 2025-12-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0003_rename_updated_at_equipment_fechaactualizacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='fechaCreacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='fechaActualizacion',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='fechaCreacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='fechaActualizacion',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='fechaCreacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='fechaActualizacion',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='fechaCreacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='fechaActualizacion',
            new_name='updated_at',
        ),
    ]
