# Generated by Django 5.0.2 on 2025-12-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0004_rename_fechacreacion_equipment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='razonCancelacion',
            new_name='cancel_reason',
        ),
    ]
